#!/usr/bin/env bash

if
  [[ -s "/home/faraz/.rvm/gems/ruby-2.4.1@learn-rails/environment" ]]
then
  source "/home/faraz/.rvm/gems/ruby-2.4.1@learn-rails/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/faraz/.rvm/gems/ruby-2.4.1@learn-rails/environment'" >&2
  exit 1
fi
